### ISSUE TITLE
dify 升级后docker容器里的docker-api-1、docker-worker-1一直restarting，dify也无法登入

### ISSUE THREAD

**Issue by WanderInTree** [laipz8200/laipz8200#1]
您好，不好意思打扰，我是通过docker本地部署的dify，我根据指引升级dify到v0.10.2后，docker-api-1、docker-worker-1一直restarting，dify也无法登入，请问是什么问题呢？我看了log，也没太看明白问题在哪儿
<img width="858" alt="1730224171264" src="https://github.com/user-attachments/assets/2fdb4e17-f15d-4ce0-96f6-99807a167799">
<img width="966" alt="1730224213091" src="https://github.com/user-attachments/assets/99b1280b-4d4d-4bef-8cca-f67b1a291a12">
<img width="966" alt="1730224236584" src="https://github.com/user-attachments/assets/016fe614-81dd-49ad-b8bc-0706388149fd">

**Comment by laipz8200** [comment]
尝试在 docker/.env 中修改或添加：

TIDB_ON_QDRANT_CLIENT_TIMEOUT=30

**Comment by WanderInTree** [comment]
尝试后，还是未解决



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月30日(周三) 凌晨2:03
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [laipz8200/laipz8200] dify 升级后docker容器里的docker-api-1、docker-worker-1一直restarting，dify也无法登入 (Issue #1)




 
尝试在 docker/.env 中修改或添加：
 
TIDB_ON_QDRANT_CLIENT_TIMEOUT=30

**Comment by WanderInTree** [comment]
已解决，感谢

**Comment by KCCADA** [comment]
> 已解决，感谢求解

**Comment by KCCADA** [comment]
怎么解决
